changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🚨 Breaking Changes
      labels:
        - breaking-change
    - title: 🎉 New Features
      labels:
        - enhancement
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 🛠️ Maintenance
      labels:
        - chore
    - title: Other Changes
      labels:
        - "*"
